
project_id = "znyvlzpirrdhorduemnv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[realtime]
enabled = true

[[functions]]
name = "create-payment-session"
verify_jwt = false

[[functions]]
name = "process-payment-success"
verify_jwt = false
