
project_id = "znyvlzpirrdhorduemnv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://preview--hairitage.lovable.app"

[storage]
enabled = true

[realtime]
enabled = true

[functions.create-payment-session]
verify_jwt = false

[functions.process-payment-success]
verify_jwt = false
